name: flutter_daylight_savings
description: Get upcoming daylight savings transitions from the system
version: 1.2.0
homepage: https://github.com/chipweinberger/flutter_daylight_savings

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lib.flutter_daylight_savings
        pluginClass: FlutterDaylightSavingsPlugin
      ios:
        pluginClass: FlutterDaylightSavingsPlugin
      macos:
        pluginClass: FlutterDaylightSavingsPlugin

